<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.2" release="Thu May 05 14:58:55 2016 -0700">
<training_set datafile="../data/e_coli/NC_000913.3/meme-chip/gyra_expo/seqs-centered" length="578">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="peak0" length="71" weight="1.000000" />
<sequence id="sequence_1" name="peak1" length="67" weight="1.000000" />
<sequence id="sequence_2" name="peak2" length="64" weight="1.000000" />
<sequence id="sequence_3" name="peak3" length="71" weight="1.000000" />
<sequence id="sequence_4" name="peak4" length="66" weight="1.000000" />
<sequence id="sequence_5" name="peak5" length="74" weight="1.000000" />
<sequence id="sequence_6" name="peak6" length="74" weight="1.000000" />
<sequence id="sequence_7" name="peak7" length="74" weight="1.000000" />
<sequence id="sequence_8" name="peak8" length="62" weight="1.000000" />
<sequence id="sequence_9" name="peak9" length="71" weight="1.000000" />
<sequence id="sequence_10" name="peak10" length="83" weight="1.000000" />
<sequence id="sequence_11" name="peak11" length="65" weight="1.000000" />
<sequence id="sequence_12" name="peak12" length="62" weight="1.000000" />
<sequence id="sequence_13" name="peak13" length="76" weight="1.000000" />
<sequence id="sequence_14" name="peak14" length="66" weight="1.000000" />
<sequence id="sequence_15" name="peak15" length="73" weight="1.000000" />
<sequence id="sequence_16" name="peak16" length="88" weight="1.000000" />
<sequence id="sequence_17" name="peak17" length="78" weight="1.000000" />
<sequence id="sequence_18" name="peak18" length="76" weight="1.000000" />
<sequence id="sequence_19" name="peak19" length="69" weight="1.000000" />
<sequence id="sequence_20" name="peak20" length="67" weight="1.000000" />
<sequence id="sequence_21" name="peak21" length="68" weight="1.000000" />
<sequence id="sequence_22" name="peak22" length="66" weight="1.000000" />
<sequence id="sequence_23" name="peak23" length="50" weight="1.000000" />
<sequence id="sequence_24" name="peak24" length="70" weight="1.000000" />
<sequence id="sequence_25" name="peak25" length="66" weight="1.000000" />
<sequence id="sequence_26" name="peak26" length="67" weight="1.000000" />
<sequence id="sequence_27" name="peak27" length="67" weight="1.000000" />
<sequence id="sequence_28" name="peak28" length="67" weight="1.000000" />
<sequence id="sequence_29" name="peak29" length="75" weight="1.000000" />
<sequence id="sequence_30" name="peak30" length="66" weight="1.000000" />
<sequence id="sequence_31" name="peak31" length="73" weight="1.000000" />
<sequence id="sequence_32" name="peak32" length="67" weight="1.000000" />
<sequence id="sequence_33" name="peak33" length="63" weight="1.000000" />
<sequence id="sequence_34" name="peak34" length="66" weight="1.000000" />
<sequence id="sequence_35" name="peak35" length="62" weight="1.000000" />
<sequence id="sequence_36" name="peak36" length="65" weight="1.000000" />
<sequence id="sequence_37" name="peak37" length="75" weight="1.000000" />
<sequence id="sequence_38" name="peak38" length="50" weight="1.000000" />
<sequence id="sequence_39" name="peak39" length="70" weight="1.000000" />
<sequence id="sequence_40" name="peak40" length="68" weight="1.000000" />
<sequence id="sequence_41" name="peak41" length="66" weight="1.000000" />
<sequence id="sequence_42" name="peak42" length="73" weight="1.000000" />
<sequence id="sequence_43" name="peak43" length="72" weight="1.000000" />
<sequence id="sequence_44" name="peak44" length="71" weight="1.000000" />
<sequence id="sequence_45" name="peak45" length="66" weight="1.000000" />
<sequence id="sequence_46" name="peak46" length="84" weight="1.000000" />
<sequence id="sequence_47" name="peak47" length="77" weight="1.000000" />
<sequence id="sequence_48" name="peak48" length="70" weight="1.000000" />
<sequence id="sequence_49" name="peak49" length="81" weight="1.000000" />
<sequence id="sequence_50" name="peak50" length="64" weight="1.000000" />
<sequence id="sequence_51" name="peak51" length="65" weight="1.000000" />
<sequence id="sequence_52" name="peak52" length="65" weight="1.000000" />
<sequence id="sequence_53" name="peak53" length="52" weight="1.000000" />
<sequence id="sequence_54" name="peak54" length="81" weight="1.000000" />
<sequence id="sequence_55" name="peak55" length="67" weight="1.000000" />
<sequence id="sequence_56" name="peak56" length="70" weight="1.000000" />
<sequence id="sequence_57" name="peak57" length="67" weight="1.000000" />
<sequence id="sequence_58" name="peak58" length="77" weight="1.000000" />
<sequence id="sequence_59" name="peak59" length="65" weight="1.000000" />
<sequence id="sequence_60" name="peak60" length="68" weight="1.000000" />
<sequence id="sequence_61" name="peak61" length="69" weight="1.000000" />
<sequence id="sequence_62" name="peak62" length="66" weight="1.000000" />
<sequence id="sequence_63" name="peak63" length="69" weight="1.000000" />
<sequence id="sequence_64" name="peak64" length="60" weight="1.000000" />
<sequence id="sequence_65" name="peak65" length="67" weight="1.000000" />
<sequence id="sequence_66" name="peak66" length="57" weight="1.000000" />
<sequence id="sequence_67" name="peak67" length="71" weight="1.000000" />
<sequence id="sequence_68" name="peak68" length="67" weight="1.000000" />
<sequence id="sequence_69" name="peak69" length="69" weight="1.000000" />
<sequence id="sequence_70" name="peak70" length="75" weight="1.000000" />
<sequence id="sequence_71" name="peak71" length="67" weight="1.000000" />
<sequence id="sequence_72" name="peak72" length="67" weight="1.000000" />
<sequence id="sequence_73" name="peak73" length="60" weight="1.000000" />
<sequence id="sequence_74" name="peak74" length="65" weight="1.000000" />
<sequence id="sequence_75" name="peak75" length="74" weight="1.000000" />
<sequence id="sequence_76" name="peak76" length="69" weight="1.000000" />
<sequence id="sequence_77" name="peak77" length="52" weight="1.000000" />
<sequence id="sequence_78" name="peak78" length="72" weight="1.000000" />
<sequence id="sequence_79" name="peak79" length="64" weight="1.000000" />
<sequence id="sequence_80" name="peak80" length="53" weight="1.000000" />
<sequence id="sequence_81" name="peak81" length="55" weight="1.000000" />
<sequence id="sequence_82" name="peak82" length="57" weight="1.000000" />
<sequence id="sequence_83" name="peak83" length="70" weight="1.000000" />
<sequence id="sequence_84" name="peak84" length="67" weight="1.000000" />
<sequence id="sequence_85" name="peak85" length="70" weight="1.000000" />
<sequence id="sequence_86" name="peak86" length="88" weight="1.000000" />
<sequence id="sequence_87" name="peak87" length="67" weight="1.000000" />
<sequence id="sequence_88" name="peak88" length="67" weight="1.000000" />
<sequence id="sequence_89" name="peak89" length="66" weight="1.000000" />
<sequence id="sequence_90" name="peak90" length="62" weight="1.000000" />
<sequence id="sequence_91" name="peak91" length="70" weight="1.000000" />
<sequence id="sequence_92" name="peak92" length="56" weight="1.000000" />
<sequence id="sequence_93" name="peak93" length="55" weight="1.000000" />
<sequence id="sequence_94" name="peak94" length="63" weight="1.000000" />
<sequence id="sequence_95" name="peak95" length="86" weight="1.000000" />
<sequence id="sequence_96" name="peak96" length="62" weight="1.000000" />
<sequence id="sequence_97" name="peak97" length="50" weight="1.000000" />
<sequence id="sequence_98" name="peak98" length="74" weight="1.000000" />
<sequence id="sequence_99" name="peak99" length="63" weight="1.000000" />
<sequence id="sequence_100" name="peak100" length="72" weight="1.000000" />
<sequence id="sequence_101" name="peak101" length="68" weight="1.000000" />
<sequence id="sequence_102" name="peak102" length="65" weight="1.000000" />
<sequence id="sequence_103" name="peak103" length="74" weight="1.000000" />
<sequence id="sequence_104" name="peak104" length="72" weight="1.000000" />
<sequence id="sequence_105" name="peak105" length="71" weight="1.000000" />
<sequence id="sequence_106" name="peak106" length="50" weight="1.000000" />
<sequence id="sequence_107" name="peak107" length="75" weight="1.000000" />
<sequence id="sequence_108" name="peak108" length="54" weight="1.000000" />
<sequence id="sequence_109" name="peak109" length="77" weight="1.000000" />
<sequence id="sequence_110" name="peak110" length="88" weight="1.000000" />
<sequence id="sequence_111" name="peak111" length="75" weight="1.000000" />
<sequence id="sequence_112" name="peak112" length="67" weight="1.000000" />
<sequence id="sequence_113" name="peak113" length="62" weight="1.000000" />
<sequence id="sequence_114" name="peak114" length="67" weight="1.000000" />
<sequence id="sequence_115" name="peak115" length="69" weight="1.000000" />
<sequence id="sequence_116" name="peak116" length="50" weight="1.000000" />
<sequence id="sequence_117" name="peak117" length="57" weight="1.000000" />
<sequence id="sequence_118" name="peak118" length="79" weight="1.000000" />
<sequence id="sequence_119" name="peak119" length="67" weight="1.000000" />
<sequence id="sequence_120" name="peak120" length="70" weight="1.000000" />
<sequence id="sequence_121" name="peak121" length="74" weight="1.000000" />
<sequence id="sequence_122" name="peak122" length="72" weight="1.000000" />
<sequence id="sequence_123" name="peak123" length="72" weight="1.000000" />
<sequence id="sequence_124" name="peak124" length="67" weight="1.000000" />
<sequence id="sequence_125" name="peak125" length="62" weight="1.000000" />
<sequence id="sequence_126" name="peak126" length="67" weight="1.000000" />
<sequence id="sequence_127" name="peak127" length="74" weight="1.000000" />
<sequence id="sequence_128" name="peak128" length="55" weight="1.000000" />
<sequence id="sequence_129" name="peak129" length="70" weight="1.000000" />
<sequence id="sequence_130" name="peak130" length="72" weight="1.000000" />
<sequence id="sequence_131" name="peak131" length="73" weight="1.000000" />
<sequence id="sequence_132" name="peak132" length="61" weight="1.000000" />
<sequence id="sequence_133" name="peak133" length="67" weight="1.000000" />
<sequence id="sequence_134" name="peak134" length="55" weight="1.000000" />
<sequence id="sequence_135" name="peak135" length="65" weight="1.000000" />
<sequence id="sequence_136" name="peak136" length="67" weight="1.000000" />
<sequence id="sequence_137" name="peak137" length="58" weight="1.000000" />
<sequence id="sequence_138" name="peak138" length="72" weight="1.000000" />
<sequence id="sequence_139" name="peak139" length="69" weight="1.000000" />
<sequence id="sequence_140" name="peak140" length="63" weight="1.000000" />
<sequence id="sequence_141" name="peak141" length="72" weight="1.000000" />
<sequence id="sequence_142" name="peak142" length="66" weight="1.000000" />
<sequence id="sequence_143" name="peak143" length="54" weight="1.000000" />
<sequence id="sequence_144" name="peak144" length="54" weight="1.000000" />
<sequence id="sequence_145" name="peak145" length="70" weight="1.000000" />
<sequence id="sequence_146" name="peak146" length="63" weight="1.000000" />
<sequence id="sequence_147" name="peak147" length="67" weight="1.000000" />
<sequence id="sequence_148" name="peak148" length="69" weight="1.000000" />
<sequence id="sequence_149" name="peak149" length="73" weight="1.000000" />
<sequence id="sequence_150" name="peak150" length="64" weight="1.000000" />
<sequence id="sequence_151" name="peak151" length="75" weight="1.000000" />
<sequence id="sequence_152" name="peak152" length="72" weight="1.000000" />
<sequence id="sequence_153" name="peak153" length="64" weight="1.000000" />
<sequence id="sequence_154" name="peak154" length="66" weight="1.000000" />
<sequence id="sequence_155" name="peak155" length="51" weight="1.000000" />
<sequence id="sequence_156" name="peak156" length="62" weight="1.000000" />
<sequence id="sequence_157" name="peak157" length="66" weight="1.000000" />
<sequence id="sequence_158" name="peak158" length="49" weight="1.000000" />
<sequence id="sequence_159" name="peak159" length="77" weight="1.000000" />
<sequence id="sequence_160" name="peak160" length="68" weight="1.000000" />
<sequence id="sequence_161" name="peak161" length="66" weight="1.000000" />
<sequence id="sequence_162" name="peak162" length="66" weight="1.000000" />
<sequence id="sequence_163" name="peak163" length="72" weight="1.000000" />
<sequence id="sequence_164" name="peak164" length="71" weight="1.000000" />
<sequence id="sequence_165" name="peak165" length="79" weight="1.000000" />
<sequence id="sequence_166" name="peak166" length="67" weight="1.000000" />
<sequence id="sequence_167" name="peak167" length="55" weight="1.000000" />
<sequence id="sequence_168" name="peak168" length="69" weight="1.000000" />
<sequence id="sequence_169" name="peak169" length="72" weight="1.000000" />
<sequence id="sequence_170" name="peak170" length="68" weight="1.000000" />
<sequence id="sequence_171" name="peak171" length="56" weight="1.000000" />
<sequence id="sequence_172" name="peak172" length="70" weight="1.000000" />
<sequence id="sequence_173" name="peak173" length="66" weight="1.000000" />
<sequence id="sequence_174" name="peak174" length="62" weight="1.000000" />
<sequence id="sequence_175" name="peak175" length="61" weight="1.000000" />
<sequence id="sequence_176" name="peak176" length="69" weight="1.000000" />
<sequence id="sequence_177" name="peak177" length="74" weight="1.000000" />
<sequence id="sequence_178" name="peak178" length="55" weight="1.000000" />
<sequence id="sequence_179" name="peak179" length="70" weight="1.000000" />
<sequence id="sequence_180" name="peak180" length="60" weight="1.000000" />
<sequence id="sequence_181" name="peak181" length="66" weight="1.000000" />
<sequence id="sequence_182" name="peak182" length="49" weight="1.000000" />
<sequence id="sequence_183" name="peak183" length="67" weight="1.000000" />
<sequence id="sequence_184" name="peak184" length="87" weight="1.000000" />
<sequence id="sequence_185" name="peak185" length="66" weight="1.000000" />
<sequence id="sequence_186" name="peak186" length="44" weight="1.000000" />
<sequence id="sequence_187" name="peak187" length="84" weight="1.000000" />
<sequence id="sequence_188" name="peak188" length="68" weight="1.000000" />
<sequence id="sequence_189" name="peak189" length="68" weight="1.000000" />
<sequence id="sequence_190" name="peak190" length="72" weight="1.000000" />
<sequence id="sequence_191" name="peak191" length="54" weight="1.000000" />
<sequence id="sequence_192" name="peak192" length="65" weight="1.000000" />
<sequence id="sequence_193" name="peak193" length="58" weight="1.000000" />
<sequence id="sequence_194" name="peak194" length="63" weight="1.000000" />
<sequence id="sequence_195" name="peak195" length="64" weight="1.000000" />
<sequence id="sequence_196" name="peak196" length="50" weight="1.000000" />
<sequence id="sequence_197" name="peak197" length="66" weight="1.000000" />
<sequence id="sequence_198" name="peak198" length="67" weight="1.000000" />
<sequence id="sequence_199" name="peak199" length="73" weight="1.000000" />
<sequence id="sequence_200" name="peak200" length="67" weight="1.000000" />
<sequence id="sequence_201" name="peak201" length="72" weight="1.000000" />
<sequence id="sequence_202" name="peak202" length="71" weight="1.000000" />
<sequence id="sequence_203" name="peak203" length="66" weight="1.000000" />
<sequence id="sequence_204" name="peak204" length="71" weight="1.000000" />
<sequence id="sequence_205" name="peak205" length="61" weight="1.000000" />
<sequence id="sequence_206" name="peak206" length="70" weight="1.000000" />
<sequence id="sequence_207" name="peak207" length="60" weight="1.000000" />
<sequence id="sequence_208" name="peak208" length="69" weight="1.000000" />
<sequence id="sequence_209" name="peak209" length="67" weight="1.000000" />
<sequence id="sequence_210" name="peak210" length="65" weight="1.000000" />
<sequence id="sequence_211" name="peak211" length="68" weight="1.000000" />
<sequence id="sequence_212" name="peak212" length="67" weight="1.000000" />
<sequence id="sequence_213" name="peak213" length="67" weight="1.000000" />
<sequence id="sequence_214" name="peak214" length="75" weight="1.000000" />
<sequence id="sequence_215" name="peak215" length="85" weight="1.000000" />
<sequence id="sequence_216" name="peak216" length="84" weight="1.000000" />
<sequence id="sequence_217" name="peak217" length="57" weight="1.000000" />
<sequence id="sequence_218" name="peak218" length="75" weight="1.000000" />
<sequence id="sequence_219" name="peak219" length="62" weight="1.000000" />
<sequence id="sequence_220" name="peak220" length="73" weight="1.000000" />
<sequence id="sequence_221" name="peak221" length="69" weight="1.000000" />
<sequence id="sequence_222" name="peak222" length="52" weight="1.000000" />
<sequence id="sequence_223" name="peak223" length="80" weight="1.000000" />
<sequence id="sequence_224" name="peak224" length="68" weight="1.000000" />
<sequence id="sequence_225" name="peak225" length="73" weight="1.000000" />
<sequence id="sequence_226" name="peak226" length="66" weight="1.000000" />
<sequence id="sequence_227" name="peak227" length="76" weight="1.000000" />
<sequence id="sequence_228" name="peak228" length="69" weight="1.000000" />
<sequence id="sequence_229" name="peak229" length="73" weight="1.000000" />
<sequence id="sequence_230" name="peak230" length="53" weight="1.000000" />
<sequence id="sequence_231" name="peak231" length="55" weight="1.000000" />
<sequence id="sequence_232" name="peak232" length="65" weight="1.000000" />
<sequence id="sequence_233" name="peak233" length="65" weight="1.000000" />
<sequence id="sequence_234" name="peak234" length="75" weight="1.000000" />
<sequence id="sequence_235" name="peak235" length="73" weight="1.000000" />
<sequence id="sequence_236" name="peak236" length="68" weight="1.000000" />
<sequence id="sequence_237" name="peak237" length="68" weight="1.000000" />
<sequence id="sequence_238" name="peak238" length="67" weight="1.000000" />
<sequence id="sequence_239" name="peak239" length="74" weight="1.000000" />
<sequence id="sequence_240" name="peak240" length="63" weight="1.000000" />
<sequence id="sequence_241" name="peak241" length="69" weight="1.000000" />
<sequence id="sequence_242" name="peak242" length="76" weight="1.000000" />
<sequence id="sequence_243" name="peak243" length="67" weight="1.000000" />
<sequence id="sequence_244" name="peak244" length="42" weight="1.000000" />
<sequence id="sequence_245" name="peak245" length="67" weight="1.000000" />
<sequence id="sequence_246" name="peak246" length="68" weight="1.000000" />
<sequence id="sequence_247" name="peak247" length="75" weight="1.000000" />
<sequence id="sequence_248" name="peak248" length="77" weight="1.000000" />
<sequence id="sequence_249" name="peak249" length="61" weight="1.000000" />
<sequence id="sequence_250" name="peak250" length="66" weight="1.000000" />
<sequence id="sequence_251" name="peak251" length="68" weight="1.000000" />
<sequence id="sequence_252" name="peak252" length="64" weight="1.000000" />
<sequence id="sequence_253" name="peak253" length="63" weight="1.000000" />
<sequence id="sequence_254" name="peak254" length="89" weight="1.000000" />
<sequence id="sequence_255" name="peak255" length="67" weight="1.000000" />
<sequence id="sequence_256" name="peak256" length="58" weight="1.000000" />
<sequence id="sequence_257" name="peak257" length="81" weight="1.000000" />
<sequence id="sequence_258" name="peak258" length="77" weight="1.000000" />
<sequence id="sequence_259" name="peak259" length="72" weight="1.000000" />
<sequence id="sequence_260" name="peak260" length="65" weight="1.000000" />
<sequence id="sequence_261" name="peak261" length="68" weight="1.000000" />
<sequence id="sequence_262" name="peak262" length="76" weight="1.000000" />
<sequence id="sequence_263" name="peak263" length="63" weight="1.000000" />
<sequence id="sequence_264" name="peak264" length="55" weight="1.000000" />
<sequence id="sequence_265" name="peak265" length="66" weight="1.000000" />
<sequence id="sequence_266" name="peak266" length="70" weight="1.000000" />
<sequence id="sequence_267" name="peak267" length="67" weight="1.000000" />
<sequence id="sequence_268" name="peak268" length="73" weight="1.000000" />
<sequence id="sequence_269" name="peak269" length="62" weight="1.000000" />
<sequence id="sequence_270" name="peak270" length="67" weight="1.000000" />
<sequence id="sequence_271" name="peak271" length="66" weight="1.000000" />
<sequence id="sequence_272" name="peak272" length="68" weight="1.000000" />
<sequence id="sequence_273" name="peak273" length="100" weight="1.000000" />
<sequence id="sequence_274" name="peak274" length="69" weight="1.000000" />
<sequence id="sequence_275" name="peak275" length="43" weight="1.000000" />
<sequence id="sequence_276" name="peak276" length="76" weight="1.000000" />
<sequence id="sequence_277" name="peak277" length="64" weight="1.000000" />
<sequence id="sequence_278" name="peak278" length="63" weight="1.000000" />
<sequence id="sequence_279" name="peak279" length="71" weight="1.000000" />
<sequence id="sequence_280" name="peak280" length="71" weight="1.000000" />
<sequence id="sequence_281" name="peak281" length="65" weight="1.000000" />
<sequence id="sequence_282" name="peak282" length="65" weight="1.000000" />
<sequence id="sequence_283" name="peak283" length="50" weight="1.000000" />
<sequence id="sequence_284" name="peak284" length="84" weight="1.000000" />
<sequence id="sequence_285" name="peak285" length="50" weight="1.000000" />
<sequence id="sequence_286" name="peak286" length="47" weight="1.000000" />
<sequence id="sequence_287" name="peak287" length="55" weight="1.000000" />
<sequence id="sequence_288" name="peak288" length="71" weight="1.000000" />
<sequence id="sequence_289" name="peak289" length="72" weight="1.000000" />
<sequence id="sequence_290" name="peak290" length="75" weight="1.000000" />
<sequence id="sequence_291" name="peak291" length="65" weight="1.000000" />
<sequence id="sequence_292" name="peak292" length="63" weight="1.000000" />
<sequence id="sequence_293" name="peak293" length="68" weight="1.000000" />
<sequence id="sequence_294" name="peak294" length="85" weight="1.000000" />
<sequence id="sequence_295" name="peak295" length="65" weight="1.000000" />
<sequence id="sequence_296" name="peak296" length="58" weight="1.000000" />
<sequence id="sequence_297" name="peak297" length="63" weight="1.000000" />
<sequence id="sequence_298" name="peak298" length="82" weight="1.000000" />
<sequence id="sequence_299" name="peak299" length="68" weight="1.000000" />
<sequence id="sequence_300" name="peak300" length="51" weight="1.000000" />
<sequence id="sequence_301" name="peak301" length="69" weight="1.000000" />
<sequence id="sequence_302" name="peak302" length="67" weight="1.000000" />
<sequence id="sequence_303" name="peak303" length="73" weight="1.000000" />
<sequence id="sequence_304" name="peak304" length="63" weight="1.000000" />
<sequence id="sequence_305" name="peak305" length="70" weight="1.000000" />
<sequence id="sequence_306" name="peak306" length="66" weight="1.000000" />
<sequence id="sequence_307" name="peak307" length="64" weight="1.000000" />
<sequence id="sequence_308" name="peak308" length="70" weight="1.000000" />
<sequence id="sequence_309" name="peak309" length="79" weight="1.000000" />
<sequence id="sequence_310" name="peak310" length="68" weight="1.000000" />
<sequence id="sequence_311" name="peak311" length="67" weight="1.000000" />
<sequence id="sequence_312" name="peak312" length="70" weight="1.000000" />
<sequence id="sequence_313" name="peak313" length="85" weight="1.000000" />
<sequence id="sequence_314" name="peak314" length="45" weight="1.000000" />