<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!-- http://zlab.bu.edu/~phaverty/SupplementalData/CisML/cisml.dtd -->
<!DOCTYPE cis-element-search[
<!ELEMENT cis-element-search (program-name, parameters, (pattern | multi-pattern-scan)*)>
<!ELEMENT program-name (#PCDATA)>
<!ELEMENT parameters (
  pattern-file, 
  sequence-file, 
  background-seq-file?,
  pattern-pvalue-cutoff?,
  sequence-pvalue-cutoff?,
  site-pvalue-cutoff?,
  sequence-filtering,
  ANY*
 )>
<!ELEMENT command-line (#PCDATA)>
<!ELEMENT pattern-file (#PCDATA)>
<!ELEMENT sequence-file (#PCDATA)>
<!ELEMENT background-seq-file (#PCDATA)>
<!ELEMENT pattern-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-pvalue-cutoff (#PCDATA)>
<!ELEMENT site-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-filtering EMPTY>
<!ELEMENT multi-pattern-scan (pattern+, ANY*)>
<!ELEMENT pattern (scanned-sequence+, ANY*)>
<!ELEMENT scanned-sequence (matched-element*, ANY*)>
<!ELEMENT matched-element (sequence)>
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST cis-element-search
xmlns:xsi CDATA #IMPLIED
xmlns:mem CDATA #IMPLIED
xsi:schemaLocation CDATA #IMPLIED
>
<!ATTLIST sequence-filtering
on-off CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ATTLIST multi-pattern-scan
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
>
<!ATTLIST pattern
accession CDATA #REQUIRED
name CDATA #REQUIRED
pvalue CDATA #IMPLIED
score CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST scanned-sequence
accession CDATA #REQUIRED
name CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
length CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST matched-element
start CDATA #REQUIRED
stop CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
clusterid CDATA #IMPLIED
>

]>
<cis-element-search
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://zlab.bu.edu/schema/cisml cisml.xsd"
  xmlns="http://zlab.bu.edu/schema/cisml"
  xmlns:mem="http://noble.gs.washington.edu/meme"
>
<program-name>fimo</program-name>
<parameters>
<pattern-file>../data/e_coli/NC_000913.3/meme-chip/mukb_expo/meme_out/meme.xml</pattern-file>
<sequence-file>../data/e_coli/NC_000913.3/meme-chip/mukb_expo/mukb_expo.txt</sequence-file>
<site-pvalue-cutoff>0.0001</site-pvalue-cutoff>
<sequence-filtering on-off="off"/>
</parameters>
<pattern accession="4" name="4">
<scanned-sequence accession="peak0" name="peak0">
</scanned-sequence>
<scanned-sequence accession="peak1" name="peak1">
<matched-element start="315" stop="327" score="10.5301" pvalue="4.8e-05">
<sequence>GTAACGAGGTAAC</sequence>
<mem:qvalue>0.234</mem:qvalue>
</matched-element>
<matched-element start="327" stop="315" score="9.20482" pvalue="8.68e-05">
<sequence>GTTACCTCGTTAC</sequence>
<mem:qvalue>0.313</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak2" name="peak2">
<matched-element start="117" stop="129" score="10.5301" pvalue="4.8e-05">
<sequence>GTAACGAGGTAAC</sequence>
<mem:qvalue>0.234</mem:qvalue>
</matched-element>
<matched-element start="129" stop="117" score="9.20482" pvalue="8.68e-05">
<sequence>GTTACCTCGTTAC</sequence>
<mem:qvalue>0.313</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak3" name="peak3">
<matched-element start="398" stop="410" score="12.2289" pvalue="2.06e-05">
<sequence>GTCACAACGTTAC</sequence>
<mem:qvalue>0.119</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak4" name="peak4">
<matched-element start="267" stop="279" score="12.2289" pvalue="2.06e-05">
<sequence>GTCACAACGTTAC</sequence>
<mem:qvalue>0.119</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak5" name="peak5">
</scanned-sequence>
<scanned-sequence accession="peak6" name="peak6">
</scanned-sequence>
<scanned-sequence accession="peak7" name="peak7">
</scanned-sequence>
<scanned-sequence accession="peak8" name="peak8">
</scanned-sequence>
<scanned-sequence accession="peak9" name="peak9">
</scanned-sequence>
<scanned-sequence accession="peak10" name="peak10">
</scanned-sequence>
<scanned-sequence accession="peak11" name="peak11">
<matched-element start="396" stop="408" score="9.79518" pvalue="6.66e-05">
<sequence>ATAAAAACGTCCC</sequence>
<mem:qvalue>0.283</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak12" name="peak12">
<matched-element start="329" stop="341" score="9.79518" pvalue="6.66e-05">
<sequence>ATAAAAACGTCCC</sequence>
<mem:qvalue>0.283</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak13" name="peak13">
</scanned-sequence>
<scanned-sequence accession="peak14" name="peak14">
</scanned-sequence>
<scanned-sequence accession="peak15" name="peak15">
</scanned-sequence>
<scanned-sequence accession="peak16" name="peak16">
</scanned-sequence>
<scanned-sequence accession="peak17" name="peak17">
</scanned-sequence>
<scanned-sequence accession="peak18" name="peak18">
<matched-element start="240" stop="252" score="14.2892" pvalue="6.75e-06">
<sequence>ATGATAGCGTCAC</sequence>
<mem:qvalue>0.0639</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak19" name="peak19">
</scanned-sequence>
<scanned-sequence accession="peak20" name="peak20">
</scanned-sequence>
<scanned-sequence accession="peak21" name="peak21">
</scanned-sequence>
<scanned-sequence accession="peak22" name="peak22">
</scanned-sequence>
<scanned-sequence accession="peak23" name="peak23">
</scanned-sequence>
<scanned-sequence accession="peak24" name="peak24">
</scanned-sequence>
<scanned-sequence accession="peak25" name="peak25">
</scanned-sequence>
<scanned-sequence accession="peak26" name="peak26">
</scanned-sequence>
<scanned-sequence accession="peak27" name="peak27">
<matched-element start="483" stop="495" score="16.1687" pvalue="1.98e-06">
<sequence>GTAACAAGGTAAC</sequence>
<mem:qvalue>0.0251</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak28" name="peak28">
<matched-element start="213" stop="225" score="16.1687" pvalue="1.98e-06">
<sequence>GTAACAAGGTAAC</sequence>
<mem:qvalue>0.0251</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak29" name="peak29">
</scanned-sequence>
<scanned-sequence accession="peak30" name="peak30">
</scanned-sequence>
<scanned-sequence accession="peak31" name="peak31">
</scanned-sequence>
<scanned-sequence accession="peak32" name="peak32">
</scanned-sequence>
<scanned-sequence accession="peak33" name="peak33">
</scanned-sequence>
<scanned-sequence accession="peak34" name="peak34">
</scanned-sequence>
<scanned-sequence accession="peak35" name="peak35">
</scanned-sequence>
<scanned-sequence accession="peak36" name="peak36">
</scanned-sequence>
<scanned-sequence accession="peak37" name="peak37">
</scanned-sequence>
<scanned-sequence accession="peak38" name="peak38">
</scanned-sequence>
<scanned-sequence accession="peak39" name="peak39">
<matched-element start="257" stop="245" score="11.2048" pvalue="3.45e-05">
<sequence>ATTACCCGGTAAC</sequence>
<mem:qvalue>0.184</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="9.40964" pvalue="7.93e-05">
<sequence>GTTACCGGGTAAT</sequence>
<mem:qvalue>0.299</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak40" name="peak40">
</scanned-sequence>
<scanned-sequence accession="peak41" name="peak41">
<matched-element start="363" stop="351" score="13.3012" pvalue="1.17e-05">
<sequence>GTTACAATGGCAC</sequence>
<mem:qvalue>0.0889</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak42" name="peak42">
<matched-element start="325" stop="313" score="13.3012" pvalue="1.17e-05">
<sequence>GTTACAATGGCAC</sequence>
<mem:qvalue>0.0889</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak43" name="peak43">
<matched-element start="257" stop="245" score="13.3012" pvalue="1.17e-05">
<sequence>GTTACAATGGCAC</sequence>
<mem:qvalue>0.0889</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak44" name="peak44">
</scanned-sequence>
<scanned-sequence accession="peak45" name="peak45">
<matched-element start="247" stop="259" score="12.4819" pvalue="1.83e-05">
<sequence>GTTACAGCGTAAA</sequence>
<mem:qvalue>0.112</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak46" name="peak46">
<matched-element start="245" stop="257" score="15.5904" pvalue="3e-06">
<sequence>GTTACAGGGTTAC</sequence>
<mem:qvalue>0.0328</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="11.5663" pvalue="2.88e-05">
<sequence>GTAACCCTGTAAC</sequence>
<mem:qvalue>0.158</mem:qvalue>
</matched-element>
<matched-element start="249" stop="237" score="11.0241" pvalue="3.8e-05">
<sequence>GTAACACGGTCAA</sequence>
<mem:qvalue>0.193</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak47" name="peak47">
</scanned-sequence>
<scanned-sequence accession="peak48" name="peak48">
</scanned-sequence>
<scanned-sequence accession="peak49" name="peak49">
<matched-element start="257" stop="245" score="12.5663" pvalue="1.74e-05">
<sequence>GTTAACAGGTCAC</sequence>
<mem:qvalue>0.109</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak50" name="peak50">
<matched-element start="245" stop="257" score="13.0843" pvalue="1.33e-05">
<sequence>GTTACTTCGTCAC</sequence>
<mem:qvalue>0.0958</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak51" name="peak51">
</scanned-sequence>
<scanned-sequence accession="peak52" name="peak52">
</scanned-sequence>
<scanned-sequence accession="peak53" name="peak53">
</scanned-sequence>
<scanned-sequence accession="peak54" name="peak54">
<matched-element start="193" stop="181" score="9.59036" pvalue="7.32e-05">
<sequence>GTGACACCATAAT</sequence>
<mem:qvalue>0.286</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak55" name="peak55">
<matched-element start="151" stop="139" score="9.59036" pvalue="7.32e-05">
<sequence>GTGACACCATAAT</sequence>
<mem:qvalue>0.286</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak56" name="peak56">
</scanned-sequence>
<scanned-sequence accession="peak57" name="peak57">
<matched-element start="246" stop="258" score="9.16867" pvalue="8.83e-05">
<sequence>GTTACAGGGTGAT</sequence>
<mem:qvalue>0.317</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak58" name="peak58">
<matched-element start="243" stop="255" score="16.494" pvalue="1.51e-06">
<sequence>ATTACACGGTCAC</sequence>
<mem:qvalue>0.0239</mem:qvalue>
</matched-element>
<matched-element start="255" stop="243" score="9.57831" pvalue="7.36e-05">
<sequence>GTGACCGTGTAAT</sequence>
<mem:qvalue>0.286</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak59" name="peak59">
</scanned-sequence>
<scanned-sequence accession="peak60" name="peak60">
</scanned-sequence>
<scanned-sequence accession="peak61" name="peak61">
</scanned-sequence>
<scanned-sequence accession="peak62" name="peak62">
</scanned-sequence>
<scanned-sequence accession="peak63" name="peak63">
</scanned-sequence>
<scanned-sequence accession="peak64" name="peak64">
</scanned-sequence>
<scanned-sequence accession="peak65" name="peak65">
</scanned-sequence>
<scanned-sequence accession="peak66" name="peak66">
</scanned-sequence>
<scanned-sequence accession="peak67" name="peak67">
</scanned-sequence>
<scanned-sequence accession="peak68" name="peak68">
</scanned-sequence>
<scanned-sequence accession="peak69" name="peak69">
</scanned-sequence>
<scanned-sequence accession="peak70" name="peak70">
</scanned-sequence>
<scanned-sequence accession="peak71" name="peak71">
<matched-element start="257" stop="245" score="12.7108" pvalue="1.61e-05">
<sequence>GAAACAACGTCAC</sequence>
<mem:qvalue>0.109</mem:qvalue>
</matched-element>
<matched-element start="17" stop="5" score="9.6506" pvalue="7.11e-05">
<sequence>GATACAGCATCAC</sequence>
<mem:qvalue>0.286</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak72" name="peak72">
</scanned-sequence>
<scanned-sequence accession="peak73" name="peak73">
</scanned-sequence>
<scanned-sequence accession="peak74" name="peak74">
</scanned-sequence>
<scanned-sequence accession="peak75" name="peak75">
</scanned-sequence>
<scanned-sequence accession="peak76" name="peak76">
<matched-element start="486" stop="498" score="9.43373" pvalue="7.85e-05">
<sequence>GTTACACTCTACC</sequence>
<mem:qvalue>0.298</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak77" name="peak77">
</scanned-sequence>
<scanned-sequence accession="peak78" name="peak78">
<matched-element start="245" stop="257" score="17.3855" pvalue="7.87e-07">
<sequence>GTTACACGGTAAC</sequence>
<mem:qvalue>0.0139</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="13.6867" pvalue="9.42e-06">
<sequence>GTTACCGTGTAAC</sequence>
<mem:qvalue>0.0797</mem:qvalue>
</matched-element>
<matched-element start="119" stop="131" score="11.7108" pvalue="2.68e-05">
<sequence>ATTATACCGTAAC</sequence>
<mem:qvalue>0.15</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak79" name="peak79">
</scanned-sequence>
<scanned-sequence accession="peak80" name="peak80">
</scanned-sequence>
<scanned-sequence accession="peak81" name="peak81">
</scanned-sequence>
<scanned-sequence accession="peak82" name="peak82">
</scanned-sequence>
<scanned-sequence accession="peak83" name="peak83">
</scanned-sequence>
<scanned-sequence accession="peak84" name="peak84">
<matched-element start="245" stop="257" score="20.9277" pvalue="2.4e-08">
<sequence>GTGACAGCGTCAC</sequence>
<mem:qvalue>0.00153</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="13.5422" pvalue="1.03e-05">
<sequence>GTGACGCTGTCAC</sequence>
<mem:qvalue>0.0846</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak85" name="peak85">
<matched-element start="245" stop="257" score="19.7108" pvalue="1.16e-07">
<sequence>GTGACAATGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="15.8675" pvalue="2.41e-06">
<sequence>GTGACATTGTCAC</sequence>
<mem:qvalue>0.0283</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak86" name="peak86">
<matched-element start="257" stop="245" score="16.2048" pvalue="1.92e-06">
<sequence>ATTACAGCGTAAC</sequence>
<mem:qvalue>0.0251</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak87" name="peak87">
</scanned-sequence>
<scanned-sequence accession="peak88" name="peak88">
<matched-element start="257" stop="245" score="15.2892" pvalue="3.67e-06">
<sequence>GTTACACCGTCAT</sequence>
<mem:qvalue>0.037</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="9.77108" pvalue="6.76e-05">
<sequence>ATGACGGTGTAAC</sequence>
<mem:qvalue>0.284</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak89" name="peak89">
<matched-element start="257" stop="245" score="19.9759" pvalue="8.97e-08">
<sequence>GTTACACCGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="12.2892" pvalue="2e-05">
<sequence>GTGACGGTGTAAC</sequence>
<mem:qvalue>0.118</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak90" name="peak90">
<matched-element start="243" stop="255" score="13.8072" pvalue="8.9e-06">
<sequence>GTTACTCGGTAAC</sequence>
<mem:qvalue>0.0784</mem:qvalue>
</matched-element>
<matched-element start="255" stop="243" score="9.72289" pvalue="6.91e-05">
<sequence>GTTACCGAGTAAC</sequence>
<mem:qvalue>0.286</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak91" name="peak91">
<matched-element start="257" stop="245" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak92" name="peak92">
</scanned-sequence>
<scanned-sequence accession="peak93" name="peak93">
</scanned-sequence>
<scanned-sequence accession="peak94" name="peak94">
<matched-element start="245" stop="257" score="19.5542" pvalue="1.4e-07">
<sequence>GTGACAGTGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="19.1807" pvalue="2.1e-07">
<sequence>GTGACACTGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak95" name="peak95">
</scanned-sequence>
<scanned-sequence accession="peak96" name="peak96">
<matched-element start="245" stop="257" score="16.6627" pvalue="1.39e-06">
<sequence>ATGACACTGTCAC</sequence>
<mem:qvalue>0.0226</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="14.8675" pvalue="4.79e-06">
<sequence>GTGACAGTGTCAT</sequence>
<mem:qvalue>0.0474</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak97" name="peak97">
<matched-element start="245" stop="257" score="12.988" pvalue="1.39e-05">
<sequence>GTGAACGGGTCAC</sequence>
<mem:qvalue>0.099</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak98" name="peak98">
<matched-element start="257" stop="245" score="20.5542" pvalue="3.5e-08">
<sequence>GTGACACCGTCAC</sequence>
<mem:qvalue>0.00185</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="13.9157" pvalue="8.35e-06">
<sequence>GTGACGGTGTCAC</sequence>
<mem:qvalue>0.0755</mem:qvalue>
</matched-element>
<matched-element start="130" stop="118" score="10.8675" pvalue="4.1e-05">
<sequence>GTAACAAGGTTCC</sequence>
<mem:qvalue>0.203</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak99" name="peak99">
<matched-element start="245" stop="257" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak100" name="peak100">
<matched-element start="257" stop="245" score="20.5542" pvalue="3.5e-08">
<sequence>GTGACACCGTCAC</sequence>
<mem:qvalue>0.00185</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="13.9157" pvalue="8.35e-06">
<sequence>GTGACGGTGTCAC</sequence>
<mem:qvalue>0.0755</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak101" name="peak101">
<matched-element start="244" stop="256" score="13.0964" pvalue="1.32e-05">
<sequence>GTGGCAGTGTAAC</sequence>
<mem:qvalue>0.0958</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak102" name="peak102">
<matched-element start="257" stop="245" score="20.9277" pvalue="2.4e-08">
<sequence>GTGACAGCGTCAC</sequence>
<mem:qvalue>0.00153</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="13.5422" pvalue="1.03e-05">
<sequence>GTGACGCTGTCAC</sequence>
<mem:qvalue>0.0846</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak103" name="peak103">
<matched-element start="244" stop="256" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="256" stop="244" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak104" name="peak104">
<matched-element start="257" stop="245" score="19.5542" pvalue="1.4e-07">
<sequence>GTGACAGTGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="19.1807" pvalue="2.1e-07">
<sequence>GTGACACTGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak105" name="peak105">
<matched-element start="257" stop="245" score="19.5542" pvalue="1.4e-07">
<sequence>GTGACAGTGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="19.1807" pvalue="2.1e-07">
<sequence>GTGACACTGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak106" name="peak106">
<matched-element start="245" stop="257" score="19.5542" pvalue="1.4e-07">
<sequence>GTGACAGTGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="19.1807" pvalue="2.1e-07">
<sequence>GTGACACTGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak107" name="peak107">
</scanned-sequence>
<scanned-sequence accession="peak108" name="peak108">
<matched-element start="257" stop="245" score="10.9759" pvalue="3.88e-05">
<sequence>ATTACGATGTCAC</sequence>
<mem:qvalue>0.195</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="10.9277" pvalue="3.98e-05">
<sequence>GTGACATCGTAAT</sequence>
<mem:qvalue>0.199</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak109" name="peak109">
<matched-element start="245" stop="257" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
<matched-element start="42" stop="54" score="8.98795" pvalue="9.55e-05">
<sequence>GTAATAAGGTCAT</sequence>
<mem:qvalue>0.336</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak110" name="peak110">
</scanned-sequence>
<scanned-sequence accession="peak111" name="peak111">
</scanned-sequence>
<scanned-sequence accession="peak112" name="peak112">
<matched-element start="245" stop="257" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak113" name="peak113">
<matched-element start="245" stop="257" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak114" name="peak114">
<matched-element start="245" stop="257" score="11.3373" pvalue="3.24e-05">
<sequence>GTGACAAACTCAC</sequence>
<mem:qvalue>0.174</mem:qvalue>
</matched-element>
<matched-element start="141" stop="129" score="9.56627" pvalue="7.41e-05">
<sequence>GTAACACCGTGCC</sequence>
<mem:qvalue>0.287</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak115" name="peak115">
<matched-element start="245" stop="257" score="18.9759" pvalue="2.57e-07">
<sequence>GTTACAGTGTCAC</sequence>
<mem:qvalue>0.0051</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="17.5542" pvalue="6.7e-07">
<sequence>GTGACACTGTAAC</sequence>
<mem:qvalue>0.0121</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak116" name="peak116">
<matched-element start="245" stop="257" score="14.4458" pvalue="6.23e-06">
<sequence>GTTACACCGTGAC</sequence>
<mem:qvalue>0.0598</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak117" name="peak117">
<matched-element start="245" stop="257" score="19.9759" pvalue="8.97e-08">
<sequence>GTTACACCGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="12.2892" pvalue="2e-05">
<sequence>GTGACGGTGTAAC</sequence>
<mem:qvalue>0.118</mem:qvalue>
</matched-element>
<matched-element start="410" stop="422" score="9.6747" pvalue="7.03e-05">
<sequence>ATTACCACATCAC</sequence>
<mem:qvalue>0.286</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak118" name="peak118">
<matched-element start="245" stop="257" score="19.5542" pvalue="1.4e-07">
<sequence>GTGACAGTGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="19.1807" pvalue="2.1e-07">
<sequence>GTGACACTGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak119" name="peak119">
<matched-element start="243" stop="255" score="19.3855" pvalue="1.84e-07">
<sequence>GTTACAGGGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
<matched-element start="255" stop="243" score="13.8916" pvalue="8.45e-06">
<sequence>GTGACCCTGTAAC</sequence>
<mem:qvalue>0.0755</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak120" name="peak120">
<matched-element start="257" stop="245" score="19.5542" pvalue="1.4e-07">
<sequence>GTGACAGTGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="19.1807" pvalue="2.1e-07">
<sequence>GTGACACTGTCAC</sequence>
<mem:qvalue>0.0043</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak121" name="peak121">
</scanned-sequence>
<scanned-sequence accession="peak122" name="peak122">
</scanned-sequence>
<scanned-sequence accession="peak123" name="peak123">
<matched-element start="257" stop="245" score="12.1687" pvalue="2.12e-05">
<sequence>ACTACAACGTCAC</sequence>
<mem:qvalue>0.121</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak124" name="peak124">
<matched-element start="244" stop="256" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="256" stop="244" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak125" name="peak125">
<matched-element start="257" stop="245" score="14.7108" pvalue="5.34e-06">
<sequence>GTTACGGCGTCAC</sequence>
<mem:qvalue>0.0521</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="13.2892" pvalue="1.18e-05">
<sequence>GTGACGCCGTAAC</sequence>
<mem:qvalue>0.0889</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak126" name="peak126">
<matched-element start="245" stop="257" score="19.9759" pvalue="8.97e-08">
<sequence>GTTACACCGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="12.2892" pvalue="2e-05">
<sequence>GTGACGGTGTAAC</sequence>
<mem:qvalue>0.118</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak127" name="peak127">
<matched-element start="257" stop="245" score="19.7108" pvalue="1.16e-07">
<sequence>GTGACAATGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="15.8675" pvalue="2.41e-06">
<sequence>GTGACATTGTCAC</sequence>
<mem:qvalue>0.0283</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak128" name="peak128">
<matched-element start="244" stop="256" score="19.9639" pvalue="1.01e-07">
<sequence>GTGACAGGGTCAC</sequence>
<mem:qvalue>0.00371</mem:qvalue>
</matched-element>
<matched-element start="256" stop="244" score="15.5181" pvalue="3.12e-06">
<sequence>GTGACCCTGTCAC</sequence>
<mem:qvalue>0.033</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak129" name="peak129">
<matched-element start="257" stop="245" score="21.0843" pvalue="1.3e-08">
<sequence>GTGACAACGTCAC</sequence>
<mem:qvalue>0.00103</mem:qvalue>
</matched-element>
<matched-element start="245" stop="257" score="10.2289" pvalue="5.47e-05">
<sequence>GTGACGTTGTCAC</sequence>
<mem:qvalue>0.248</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak130" name="peak130">
</scanned-sequence>
<scanned-sequence accession="peak131" name="peak131">
<matched-element start="257" stop="245" score="18.8795" pvalue="2.89e-07">
<sequence>GTTACAACGTAAC</sequence>
<mem:qvalue>0.00555</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak132" name="peak132">
</scanned-sequence>
<scanned-sequence accession="peak133" name="peak133">
</scanned-sequence>
<scanned-sequence accession="peak134" name="peak134">
<matched-element start="231" stop="243" score="15.6988" pvalue="2.79e-06">
<sequence>GTTACAGCATCAC</sequence>
<mem:qvalue>0.0311</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak135" name="peak135">
<matched-element start="245" stop="257" score="12.8554" pvalue="1.5e-05">
<sequence>GTTACAATATAAC</sequence>
<mem:qvalue>0.106</mem:qvalue>
</matched-element>
<matched-element start="257" stop="245" score="9.54217" pvalue="7.49e-05">
<sequence>GTTATATTGTAAC</sequence>
<mem:qvalue>0.288</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="peak136" name="peak136">
</scanned-sequence>
<scanned-sequence accession="peak137" name="peak137">
</scanned-sequence>
<scanned-sequence accession="peak138" name="peak138">
</scanned-sequence>
<scanned-sequence accession="peak139" name="peak139">
</scanned-sequence>