<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.2" release="Thu May 05 14:58:55 2016 -0700">
<training_set datafile="../data/e_coli/NC_000913.3/meme-chip/mixed-tfs-pool1a_M9+glu/seqs-centered" length="52">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="peak0" length="100" weight="1.000000" />
<sequence id="sequence_1" name="peak1" length="100" weight="1.000000" />
<sequence id="sequence_2" name="peak2" length="100" weight="1.000000" />
<sequence id="sequence_3" name="peak3" length="100" weight="1.000000" />
<sequence id="sequence_4" name="peak4" length="100" weight="1.000000" />
<sequence id="sequence_5" name="peak5" length="100" weight="1.000000" />
<sequence id="sequence_6" name="peak6" length="100" weight="1.000000" />
<sequence id="sequence_7" name="peak7" length="100" weight="1.000000" />
<sequence id="sequence_8" name="peak8" length="100" weight="1.000000" />
<sequence id="sequence_9" name="peak9" length="100" weight="1.000000" />
<sequence id="sequence_10" name="peak10" length="100" weight="1.000000" />
<sequence id="sequence_11" name="peak11" length="100" weight="1.000000" />
<sequence id="sequence_12" name="peak12" length="100" weight="1.000000" />
<sequence id="sequence_13" name="peak13" length="100" weight="1.000000" />
<sequence id="sequence_14" name="peak14" length="100" weight="1.000000" />
<sequence id="sequence_15" name="peak15" length="100" weight="1.000000" />
<sequence id="sequence_16" name="peak16" length="100" weight="1.000000" />
<sequence id="sequence_17" name="peak17" length="100" weight="1.000000" />
<sequence id="sequence_18" name="peak18" length="100" weight="1.000000" />
<sequence id="sequence_19" name="peak19" length="100" weight="1.000000" />
<sequence id="sequence_20" name="peak20" length="100" weight="1.000000" />
<sequence id="sequence_21" name="peak21" length="100" weight="1.000000" />
<sequence id="sequence_22" name="peak22" length="100" weight="1.000000" />
<sequence id="sequence_23" name="peak23" length="100" weight="1.000000" />
<sequence id="sequence_24" name="peak24" length="100" weight="1.000000" />
<sequence id="sequence_25" name="peak25" length="100" weight="1.000000" />
<sequence id="sequence_26" name="peak26" length="100" weight="1.000000" />
<sequence id="sequence_27" name="peak27" length="100" weight="1.000000" />
<sequence id="sequence_28" name="peak28" length="100" weight="1.000000" />
<sequence id="sequence_29" name="peak29" length="100" weight="1.000000" />
<sequence id="sequence_30" name="peak30" length="100" weight="1.000000" />
<sequence id="sequence_31" name="peak31" length="100" weight="1.000000" />
<sequence id="sequence_32" name="peak32" length="100" weight="1.000000" />
<sequence id="sequence_33" name="peak33" length="100" weight="1.000000" />
<sequence id="sequence_34" name="peak34" length="100" weight="1.000000" />
<sequence id="sequence_35" name="peak35" length="100" weight="1.000000" />
<sequence id="sequence_36" name="peak36" length="100" weight="1.000000" />
<sequence id="sequence_37" name="peak37" length="100" weight="1.000000" />
<sequence id="sequence_38" name="peak38" length="100" weight="1.000000" />
<sequence id="sequence_39" name="peak39" length="100" weight="1.000000" />
<sequence id="sequence_40" name="peak40" length="100" weight="1.000000" />
<sequence id="sequence_41" name="peak41" length="100" weight="1.000000" />
<sequence id="sequence_42" name="peak42" length="100" weight="1.000000" />
<sequence id="sequence_43" name="peak43" length="100" weight="1.000000" />
<sequence id="sequence_44" name="peak44" length="100" weight="1.000000" />
<sequence id="sequence_45" name="peak45" length="100" weight="1.000000" />
<sequence id="sequence_46" name="peak46" length="100" weight="1.000000" />
<sequence id="sequence_47" name="peak47" length="100" weight="1.000000" />
<sequence id="sequence_48" name="peak48" length="100" weight="1.000000" />
<sequence id="sequence_49" name="peak49" length="100" weight="1.000000" />
<sequence id="sequence_50" name="peak50" length="100" weight="1.000000" />
<sequence id="sequence_51" name="peak51" length="100" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.267</value>
<value letter_id="C">0.233</value>
<value letter_id="G">0.233</value>
<value letter_id="T">0.267</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme ../data/e_coli/NC_000913.3/meme-chip/mixed-tfs-pool1a_M9+glu/seqs-centered -oc ../data/e_coli/NC_000913.3/meme-chip/mixed-tfs-pool1a_M9+glu/meme_out -mod zoops -nmotifs 4 -minw 6 -maxw 40 -bfile ../data/e_coli/NC_000913.3/meme-chip/mixed-tfs-pool1a_M9+glu/background -dna -time 4054 -revcomp -nostatus </command_line>
<host>default-6f200c6b-e643-40e7-8f86-a4e24334f1e8</host>
<type>zoops</type>
<nmotifs>4</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>6</min_width>
<max_width>40</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>52</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>52</num_sequences>
<num_positions>5200</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (4) found.</reason_for_stopping>
<background_frequencies source="../data/e_coli/NC_000913.3/meme-chip/mixed-tfs-pool1a_M9+glu/background">
<alphabet_array>
<value letter_id="A">0.268</value>
<value letter_id="C">0.232</value>
<value letter_id="G">0.232</value>
<value letter_id="T">0.268</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="15" sites="17" ic="18.9" re="18.8" llr="221" e_value="8.0e-017" bayes_threshold="8.83076" elapsed_time="1.735490">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">34</value>
<value letter_id="G">-1073</value>
<value letter_id="T">114</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-60</value>
<value letter_id="C">-1073</value>
<value letter_id="G">-1073</value>
<value letter_id="T">162</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">-198</value>
<value letter_id="G">182</value>
<value letter_id="T">-1073</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">190</value>
<value letter_id="C">-1073</value>
<value letter_id="G">-1073</value>
<value letter_id="T">-1073</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">181</value>
<value letter_id="C">-198</value>
<value letter_id="G">-1073</value>
<value letter_id="T">-1073</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">81</value>
<value letter_id="C">-98</value>
<value letter_id="G">-98</value>
<value letter_id="T">14</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1073</value>
<value letter_id="C">172</value>
<value letter_id="G">-40</value>
<value letter_id="T">-218</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-218</value>
<value letter_id="C">-98</value>
<value letter_id="G">182</value>
<value letter_id="T">-1073</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">98</value>
<value letter_id="C">-40</value>
<value letter_id="G">-1073</value>
<value letter_id="T">14</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1073</value>
<value letter_id="C">-1073</value>
<value letter_id="G">2</value>
<value letter_id="T">151</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">-1073</value>
<value letter_id="G">-1073</value>
<value letter_id="T">172</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1073</value>
<value letter_id="C">202</value>
<value letter_id="G">-1073</value>
<value letter_id="T">-218</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">162</value>
<value letter_id="C">-40</value>
<value letter_id="G">-1073</value>
<value letter_id="T">-1073</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1073</value>
<value letter_id="C">-198</value>
<value letter_id="G">192</value>
<value letter_id="T">-218</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1073</value>
<value letter_id="C">210</value>
<value letter_id="G">-1073</value>
<value letter_id="T">-1073</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.117647</value>
<value letter_id="C">0.294118</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.588235</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.176471</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.823529</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.117647</value>
<value letter_id="C">0.058824</value>
<value letter_id="G">0.823529</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.941176</value>
<value letter_id="C">0.058824</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.470588</value>
<value letter_id="C">0.117647</value>
<value letter_id="G">0.117647</value>
<value letter_id="T">0.294118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.764706</value>
<value letter_id="G">0.176471</value>
<value letter_id="T">0.058824</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.058824</value>
<value letter_id="C">0.117647</value>
<value letter_id="G">0.823529</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.529412</value>
<value letter_id="C">0.176471</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.294118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.235294</value>
<value letter_id="T">0.764706</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.117647</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.882353</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.941176</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.058824</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.823529</value>
<value letter_id="C">0.176471</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.058824</value>
<value letter_id="G">0.882353</value>
<value letter_id="T">0.058824</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[TC]TGAA[AT]CG[AT][TG]TCAGC
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_23" position="44" strand="plus" pvalue="1.11e-09" >
<left_flank>TCTTGCTGAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CTCTATGAGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_36" position="46" strand="plus" pvalue="1.81e-08" >
<left_flank>ATTTAATCGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TAGGATAAGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_35" position="44" strand="plus" pvalue="1.81e-08" >
<left_flank>ATTTAATCGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TAGGATAAGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_14" position="46" strand="plus" pvalue="5.82e-08" >
<left_flank>CAATTGACTC</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ACTTTGGACT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_25" position="23" strand="minus" pvalue="7.37e-08" >
<left_flank>GGTTCGAAGG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AAAATGGACC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_24" position="21" strand="minus" pvalue="7.37e-08" >
<left_flank>GGTTCGAAGG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AAAATGGACC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_4" position="40" strand="minus" pvalue="1.27e-07" >
<left_flank>CTCATTAAGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AAATGATAAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_9" position="59" strand="minus" pvalue="2.37e-07" >
<left_flank>AAAAGCGATG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTTGCAAAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_50" position="47" strand="plus" pvalue="3.12e-07" >
<left_flank>TTGGCCTGAC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AGGAAGTGAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_16" position="62" strand="plus" pvalue="3.79e-07" >
<left_flank>GTCGCAATGA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTGACGCTGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_28" position="61" strand="minus" pvalue="4.17e-07" >
<left_flank>AACCAAATCA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTTGGCTTTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_31" position="23" strand="minus" pvalue="1.10e-06" >
<left_flank>CGGTGGGCTG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>GTCAACATCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_15" position="42" strand="minus" pvalue="1.28e-06" >
<left_flank>TCAACGGTTG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AACTTATTCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_12" position="52" strand="plus" pvalue="1.85e-06" >
<left_flank>TGCAAAATTT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AAATATTACC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_7" position="1" strand="plus" pvalue="2.98e-06" >
<left_flank>G</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CGTCAAACAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_11" position="73" strand="minus" pvalue="6.55e-06" >
<left_flank>ACGACACGTA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ATAGCCTACA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_34" position="70" strand="plus" pvalue="8.10e-06" >
<left_flank>GAACCAAGGG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CTGCGGCGGC</right_flank>
</contributing_site>
</contributing_sites>
</motif>
<motif id="motif_2" name="2" width="39" sites="7" ic="44.6" re="45.2" llr="219" e_value="1.0e-013" bayes_threshold="7.82045" elapsed_time="3.312133">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">168</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">-90</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">188</value>
<value letter_id="T">-90</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">168</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">-90</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">68</value>
<value letter_id="C">-945</value>
<value letter_id="G">130</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">210</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">68</value>
<value letter_id="C">-945</value>
<value letter_id="G">130</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">130</value>
<value letter_id="G">30</value>
<value letter_id="T">-90</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">162</value>
<value letter_id="G">-70</value>
<value letter_id="T">-90</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-90</value>
<value letter_id="C">-945</value>
<value letter_id="G">88</value>
<value letter_id="T">68</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">130</value>